[toolchain]
channel = "nightly"
components = ["rustc", "rustfmt", "clippy", "rust-docs", "rust-analyzer", "miri"]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown", "wasm32-wasi", "aarch64-apple-darwin"]
profile = "complete"
